spring:
  application:
    name: service-registry

server:
  port: 8180
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 5000
    service-url:
      defaultZone: http://localhost:8180/eureka

zuul:
  prefix: /api
  routes:
    payment-service:
      path: /payment-rest/**
      url: http://localhost:8184
    image-service:
      path: /images/**
      url: http://localhost:8183
    customer-service:
      path: /customer-rest/**
      url: http://localhost:8182
    catalogue-service:
      path: /catalogue-rest/**
      url: http://localhost:8181