version: 0.2

env:
  git-credential-helper: yes
  secrets-manager:
    repourlfrontend: wrkshpSecrets:repourlfrontend
    repourlbackend: wrkshpSecrets:repourlbackend

phases:
  build:
    commands:
     - git config --global user.email "workshopuser@cognizant.com"
     - git config --global user.name "workshopuser"
     - git clone $repourlfrontend
     - cd awswrkshp-aut-frontend
     - cp -R ../frontend/* .
     - git add *
     - git commit -m "init commit"
     - git push
     - cd ..
     - git clone $repourlbackend
     - cd awswrkshp-aut-backend
     - cp -R ../backend/* .
     - git add *
     - git commit -m "init commit"
     - git push
     - cd ..
